//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tantirta")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mitsubishi.MXOPC")]
        public string OPCServer1 {
            get {
                return ((string)(this["OPCServer1"]));
            }
            set {
                this["OPCServer1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string OPCHost {
            get {
                return ((string)(this["OPCHost"]));
            }
            set {
                this["OPCHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool auto_connect_opc {
            get {
                return ((bool)(this["auto_connect_opc"]));
            }
            set {
                this["auto_connect_opc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank T1")]
        public string fl1_label_tf1 {
            get {
                return ((string)(this["fl1_label_tf1"]));
            }
            set {
                this["fl1_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank T2")]
        public string fl1_label_tf2 {
            get {
                return ((string)(this["fl1_label_tf2"]));
            }
            set {
                this["fl1_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank T3")]
        public string fl1_label_tf3 {
            get {
                return ((string)(this["fl1_label_tf3"]));
            }
            set {
                this["fl1_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank T4")]
        public string fl1_label_tf4 {
            get {
                return ((string)(this["fl1_label_tf4"]));
            }
            set {
                this["fl1_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank T5")]
        public string fl1_label_tf5 {
            get {
                return ((string)(this["fl1_label_tf5"]));
            }
            set {
                this["fl1_label_tf5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Rate 1")]
        public string fl1_header {
            get {
                return ((string)(this["fl1_header"]));
            }
            set {
                this["fl1_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank A1")]
        public string fl2_label_tf1 {
            get {
                return ((string)(this["fl2_label_tf1"]));
            }
            set {
                this["fl2_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank A2")]
        public string fl2_label_tf2 {
            get {
                return ((string)(this["fl2_label_tf2"]));
            }
            set {
                this["fl2_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank B1")]
        public string fl2_label_tf3 {
            get {
                return ((string)(this["fl2_label_tf3"]));
            }
            set {
                this["fl2_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank B2")]
        public string fl2_label_tf4 {
            get {
                return ((string)(this["fl2_label_tf4"]));
            }
            set {
                this["fl2_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Rate 2")]
        public string fl2_header {
            get {
                return ((string)(this["fl2_header"]));
            }
            set {
                this["fl2_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string DatabaseServer {
            get {
                return ((string)(this["DatabaseServer"]));
            }
            set {
                this["DatabaseServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flowmeter_db")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log_data_1_2")]
        public string tabel_db_flowmeter_1_2 {
            get {
                return ((string)(this["tabel_db_flowmeter_1_2"]));
            }
            set {
                this["tabel_db_flowmeter_1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log_data_3_4_5")]
        public string tabel_db_flowmeter_3_4_5 {
            get {
                return ((string)(this["tabel_db_flowmeter_3_4_5"]));
            }
            set {
                this["tabel_db_flowmeter_3_4_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 01")]
        public string fl1_label_batch1 {
            get {
                return ((string)(this["fl1_label_batch1"]));
            }
            set {
                this["fl1_label_batch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 02")]
        public string fl1_label_batch2 {
            get {
                return ((string)(this["fl1_label_batch2"]));
            }
            set {
                this["fl1_label_batch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 03")]
        public string fl1_label_batch3 {
            get {
                return ((string)(this["fl1_label_batch3"]));
            }
            set {
                this["fl1_label_batch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 04")]
        public string fl1_label_batch4 {
            get {
                return ((string)(this["fl1_label_batch4"]));
            }
            set {
                this["fl1_label_batch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 05")]
        public string fl1_label_batch5 {
            get {
                return ((string)(this["fl1_label_batch5"]));
            }
            set {
                this["fl1_label_batch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 06")]
        public string fl1_label_batch6 {
            get {
                return ((string)(this["fl1_label_batch6"]));
            }
            set {
                this["fl1_label_batch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 07")]
        public string fl1_label_batch7 {
            get {
                return ((string)(this["fl1_label_batch7"]));
            }
            set {
                this["fl1_label_batch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 08")]
        public string fl1_label_batch8 {
            get {
                return ((string)(this["fl1_label_batch8"]));
            }
            set {
                this["fl1_label_batch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 09")]
        public string fl1_label_batch9 {
            get {
                return ((string)(this["fl1_label_batch9"]));
            }
            set {
                this["fl1_label_batch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 10")]
        public string fl1_label_batch10 {
            get {
                return ((string)(this["fl1_label_batch10"]));
            }
            set {
                this["fl1_label_batch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 01")]
        public string fl2_label_batch1 {
            get {
                return ((string)(this["fl2_label_batch1"]));
            }
            set {
                this["fl2_label_batch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 02")]
        public string fl2_label_batch2 {
            get {
                return ((string)(this["fl2_label_batch2"]));
            }
            set {
                this["fl2_label_batch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 03")]
        public string fl2_label_batch3 {
            get {
                return ((string)(this["fl2_label_batch3"]));
            }
            set {
                this["fl2_label_batch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 04")]
        public string fl2_label_batch4 {
            get {
                return ((string)(this["fl2_label_batch4"]));
            }
            set {
                this["fl2_label_batch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 05")]
        public string fl2_label_batch5 {
            get {
                return ((string)(this["fl2_label_batch5"]));
            }
            set {
                this["fl2_label_batch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 06")]
        public string fl2_label_batch6 {
            get {
                return ((string)(this["fl2_label_batch6"]));
            }
            set {
                this["fl2_label_batch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 07")]
        public string fl2_label_batch7 {
            get {
                return ((string)(this["fl2_label_batch7"]));
            }
            set {
                this["fl2_label_batch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 08")]
        public string fl2_label_batch8 {
            get {
                return ((string)(this["fl2_label_batch8"]));
            }
            set {
                this["fl2_label_batch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 09")]
        public string fl2_label_batch9 {
            get {
                return ((string)(this["fl2_label_batch9"]));
            }
            set {
                this["fl2_label_batch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Batch 10")]
        public string fl2_label_batch10 {
            get {
                return ((string)(this["fl2_label_batch10"]));
            }
            set {
                this["fl2_label_batch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Rate 3")]
        public string fl3_header {
            get {
                return ((string)(this["fl3_header"]));
            }
            set {
                this["fl3_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 1")]
        public string fl3_label_tf1 {
            get {
                return ((string)(this["fl3_label_tf1"]));
            }
            set {
                this["fl3_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 2")]
        public string fl3_label_tf2 {
            get {
                return ((string)(this["fl3_label_tf2"]));
            }
            set {
                this["fl3_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 3")]
        public string fl3_label_tf3 {
            get {
                return ((string)(this["fl3_label_tf3"]));
            }
            set {
                this["fl3_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PHE")]
        public string fl3_label_pm1 {
            get {
                return ((string)(this["fl3_label_pm1"]));
            }
            set {
                this["fl3_label_pm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHT")]
        public string fl3_label_pm2 {
            get {
                return ((string)(this["fl3_label_pm2"]));
            }
            set {
                this["fl3_label_pm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Rate 4")]
        public string fl4_header {
            get {
                return ((string)(this["fl4_header"]));
            }
            set {
                this["fl4_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 1")]
        public string fl4_label_tf1 {
            get {
                return ((string)(this["fl4_label_tf1"]));
            }
            set {
                this["fl4_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 2")]
        public string fl4_label_tf2 {
            get {
                return ((string)(this["fl4_label_tf2"]));
            }
            set {
                this["fl4_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 3")]
        public string fl4_label_tf3 {
            get {
                return ((string)(this["fl4_label_tf3"]));
            }
            set {
                this["fl4_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHT")]
        public string fl4_label_pm1 {
            get {
                return ((string)(this["fl4_label_pm1"]));
            }
            set {
                this["fl4_label_pm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PHE")]
        public string fl4_label_pm2 {
            get {
                return ((string)(this["fl4_label_pm2"]));
            }
            set {
                this["fl4_label_pm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Rate 5")]
        public string fl5_header {
            get {
                return ((string)(this["fl5_header"]));
            }
            set {
                this["fl5_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 1")]
        public string fl5_label_tf1 {
            get {
                return ((string)(this["fl5_label_tf1"]));
            }
            set {
                this["fl5_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 2")]
        public string fl5_label_tf2 {
            get {
                return ((string)(this["fl5_label_tf2"]));
            }
            set {
                this["fl5_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin MF 3")]
        public string fl5_label_tf3 {
            get {
                return ((string)(this["fl5_label_tf3"]));
            }
            set {
                this["fl5_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DJ")]
        public string fl5_label_pm1 {
            get {
                return ((string)(this["fl5_label_pm1"]));
            }
            set {
                this["fl5_label_pm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHT")]
        public string fl5_label_pm2 {
            get {
                return ((string)(this["fl5_label_pm2"]));
            }
            set {
                this["fl5_label_pm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stroberi")]
        public string fl3_produk1 {
            get {
                return ((string)(this["fl3_produk1"]));
            }
            set {
                this["fl3_produk1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anggur")]
        public string fl3_produk2 {
            get {
                return ((string)(this["fl3_produk2"]));
            }
            set {
                this["fl3_produk2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lemon")]
        public string fl3_produk3 {
            get {
                return ((string)(this["fl3_produk3"]));
            }
            set {
                this["fl3_produk3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jeruk")]
        public string fl3_produk4 {
            get {
                return ((string)(this["fl3_produk4"]));
            }
            set {
                this["fl3_produk4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jambu")]
        public string fl3_produk5 {
            get {
                return ((string)(this["fl3_produk5"]));
            }
            set {
                this["fl3_produk5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asam Jawa")]
        public string fl3_produk6 {
            get {
                return ((string)(this["fl3_produk6"]));
            }
            set {
                this["fl3_produk6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teh Manis")]
        public string fl3_produk7 {
            get {
                return ((string)(this["fl3_produk7"]));
            }
            set {
                this["fl3_produk7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 1")]
        public string fl3_produk8 {
            get {
                return ((string)(this["fl3_produk8"]));
            }
            set {
                this["fl3_produk8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 2")]
        public string fl3_produk9 {
            get {
                return ((string)(this["fl3_produk9"]));
            }
            set {
                this["fl3_produk9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 3")]
        public string fl3_produk10 {
            get {
                return ((string)(this["fl3_produk10"]));
            }
            set {
                this["fl3_produk10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 4")]
        public string fl3_produk11 {
            get {
                return ((string)(this["fl3_produk11"]));
            }
            set {
                this["fl3_produk11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stroberi")]
        public string fl4_produk1 {
            get {
                return ((string)(this["fl4_produk1"]));
            }
            set {
                this["fl4_produk1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anggur")]
        public string fl4_produk2 {
            get {
                return ((string)(this["fl4_produk2"]));
            }
            set {
                this["fl4_produk2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lemon")]
        public string fl4_produk3 {
            get {
                return ((string)(this["fl4_produk3"]));
            }
            set {
                this["fl4_produk3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jeruk")]
        public string fl4_produk4 {
            get {
                return ((string)(this["fl4_produk4"]));
            }
            set {
                this["fl4_produk4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jambu")]
        public string fl4_produk5 {
            get {
                return ((string)(this["fl4_produk5"]));
            }
            set {
                this["fl4_produk5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asam Jawa")]
        public string fl4_produk6 {
            get {
                return ((string)(this["fl4_produk6"]));
            }
            set {
                this["fl4_produk6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teh Manis")]
        public string fl4_produk7 {
            get {
                return ((string)(this["fl4_produk7"]));
            }
            set {
                this["fl4_produk7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 1")]
        public string fl4_produk8 {
            get {
                return ((string)(this["fl4_produk8"]));
            }
            set {
                this["fl4_produk8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 2")]
        public string fl4_produk9 {
            get {
                return ((string)(this["fl4_produk9"]));
            }
            set {
                this["fl4_produk9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 3")]
        public string fl4_produk10 {
            get {
                return ((string)(this["fl4_produk10"]));
            }
            set {
                this["fl4_produk10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 4")]
        public string fl4_produk11 {
            get {
                return ((string)(this["fl4_produk11"]));
            }
            set {
                this["fl4_produk11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stroberi")]
        public string fl5_produk1 {
            get {
                return ((string)(this["fl5_produk1"]));
            }
            set {
                this["fl5_produk1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anggur")]
        public string fl5_produk2 {
            get {
                return ((string)(this["fl5_produk2"]));
            }
            set {
                this["fl5_produk2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lemon")]
        public string fl5_produk3 {
            get {
                return ((string)(this["fl5_produk3"]));
            }
            set {
                this["fl5_produk3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jeruk")]
        public string fl5_produk4 {
            get {
                return ((string)(this["fl5_produk4"]));
            }
            set {
                this["fl5_produk4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jambu")]
        public string fl5_produk5 {
            get {
                return ((string)(this["fl5_produk5"]));
            }
            set {
                this["fl5_produk5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asam Jawa")]
        public string fl5_produk6 {
            get {
                return ((string)(this["fl5_produk6"]));
            }
            set {
                this["fl5_produk6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teh Manis")]
        public string fl5_produk7 {
            get {
                return ((string)(this["fl5_produk7"]));
            }
            set {
                this["fl5_produk7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 1")]
        public string fl5_produk8 {
            get {
                return ((string)(this["fl5_produk8"]));
            }
            set {
                this["fl5_produk8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 2")]
        public string fl5_produk9 {
            get {
                return ((string)(this["fl5_produk9"]));
            }
            set {
                this["fl5_produk9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 3")]
        public string fl5_produk10 {
            get {
                return ((string)(this["fl5_produk10"]));
            }
            set {
                this["fl5_produk10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baru 4")]
        public string fl5_produk11 {
            get {
                return ((string)(this["fl5_produk11"]));
            }
            set {
                this["fl5_produk11"] = value;
            }
        }
    }
}
