//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tantirta")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mitsubishi.MXOPC")]
        public string OPCServer1 {
            get {
                return ((string)(this["OPCServer1"]));
            }
            set {
                this["OPCServer1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string OPCHost {
            get {
                return ((string)(this["OPCHost"]));
            }
            set {
                this["OPCHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_connect_opc {
            get {
                return ((bool)(this["auto_connect_opc"]));
            }
            set {
                this["auto_connect_opc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 1")]
        public string fl1_label_tf1 {
            get {
                return ((string)(this["fl1_label_tf1"]));
            }
            set {
                this["fl1_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 2")]
        public string fl1_label_tf2 {
            get {
                return ((string)(this["fl1_label_tf2"]));
            }
            set {
                this["fl1_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 3")]
        public string fl1_label_tf3 {
            get {
                return ((string)(this["fl1_label_tf3"]));
            }
            set {
                this["fl1_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 4")]
        public string fl1_label_tf4 {
            get {
                return ((string)(this["fl1_label_tf4"]));
            }
            set {
                this["fl1_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Meter UHT 1")]
        public string fl1_header {
            get {
                return ((string)(this["fl1_header"]));
            }
            set {
                this["fl1_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHT 1")]
        public string fl1_label_sumber1 {
            get {
                return ((string)(this["fl1_label_sumber1"]));
            }
            set {
                this["fl1_label_sumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 1")]
        public string fl2_label_tf1 {
            get {
                return ((string)(this["fl2_label_tf1"]));
            }
            set {
                this["fl2_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 2")]
        public string fl2_label_tf2 {
            get {
                return ((string)(this["fl2_label_tf2"]));
            }
            set {
                this["fl2_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 3")]
        public string fl2_label_tf3 {
            get {
                return ((string)(this["fl2_label_tf3"]));
            }
            set {
                this["fl2_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mesin 4")]
        public string fl2_label_tf4 {
            get {
                return ((string)(this["fl2_label_tf4"]));
            }
            set {
                this["fl2_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Meter UHT 2")]
        public string fl2_header {
            get {
                return ((string)(this["fl2_header"]));
            }
            set {
                this["fl2_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHT 2")]
        public string fl2_label_sumber1 {
            get {
                return ((string)(this["fl2_label_sumber1"]));
            }
            set {
                this["fl2_label_sumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 1")]
        public string fl3_label_tf1 {
            get {
                return ((string)(this["fl3_label_tf1"]));
            }
            set {
                this["fl3_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 2")]
        public string fl3_label_tf2 {
            get {
                return ((string)(this["fl3_label_tf2"]));
            }
            set {
                this["fl3_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 3")]
        public string fl3_label_tf3 {
            get {
                return ((string)(this["fl3_label_tf3"]));
            }
            set {
                this["fl3_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 4")]
        public string fl3_label_tf4 {
            get {
                return ((string)(this["fl3_label_tf4"]));
            }
            set {
                this["fl3_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Meter Tank Double Jaket 1")]
        public string fl3_header {
            get {
                return ((string)(this["fl3_header"]));
            }
            set {
                this["fl3_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sumber RO")]
        public string fl3_label_sumber1 {
            get {
                return ((string)(this["fl3_label_sumber1"]));
            }
            set {
                this["fl3_label_sumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Air")]
        public string fl3_label_sumber2 {
            get {
                return ((string)(this["fl3_label_sumber2"]));
            }
            set {
                this["fl3_label_sumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 1")]
        public string fl4_label_tf1 {
            get {
                return ((string)(this["fl4_label_tf1"]));
            }
            set {
                this["fl4_label_tf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 2")]
        public string fl4_label_tf2 {
            get {
                return ((string)(this["fl4_label_tf2"]));
            }
            set {
                this["fl4_label_tf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 3")]
        public string fl4_label_tf3 {
            get {
                return ((string)(this["fl4_label_tf3"]));
            }
            set {
                this["fl4_label_tf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tank 4")]
        public string fl4_label_tf4 {
            get {
                return ((string)(this["fl4_label_tf4"]));
            }
            set {
                this["fl4_label_tf4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flow Meter Tank Double Jaket 2")]
        public string fl4_header {
            get {
                return ((string)(this["fl4_header"]));
            }
            set {
                this["fl4_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sumber RO")]
        public string fl4_label_sumber1 {
            get {
                return ((string)(this["fl4_label_sumber1"]));
            }
            set {
                this["fl4_label_sumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Air")]
        public string fl4_label_sumber2 {
            get {
                return ((string)(this["fl4_label_sumber2"]));
            }
            set {
                this["fl4_label_sumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string DatabaseServer {
            get {
                return ((string)(this["DatabaseServer"]));
            }
            set {
                this["DatabaseServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("flow_meter_db")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log_data")]
        public string tabel_db_flowmeter {
            get {
                return ((string)(this["tabel_db_flowmeter"]));
            }
            set {
                this["tabel_db_flowmeter"] = value;
            }
        }
    }
}
